---
transporters: ~
dots: |
  pygrrppp
  ryypggpy
  ggrgrggp
  -yyyryb-
  --rbbp--
  gyyygygr
  y--pp--p
  rgpgrggp
iceOverlay: |
  -------2
  2------2
  --------
  --------
  --------
  --------
  ----1---
  1---23--